#!/bin/bash

eval "$(oh-my-posh prompt init zsh --config ~/.prompt.json)"
source $(brew --prefix)/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

if [[ -e ~/.prompt.local ]]; then
	source ~/.prompt.local
fi
