#!/bin/bash

alias reload!=". ~/.zshrc"

alias ..="cd ../"
alias ...="cd ../../"
alias ....="cd ../../../"

alias cp="cp -iv"
alias mkdir="mkdir -pv"
alias mv="mv -iv"
alias c="clear"
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"

alias pip="pip3.9"
alias python="python3.9"

alias chrome="chrome-cli"
alias ls="exa --icons"

alias lg="lazygit"
# Load OS specific configs

. "$HOME/.mac.aliases"
