# /bin/zsh
#
# ▄▄▄ .• ▌ ▄ ·. • ▌ ▄ ·.  ▄▄▄· 
# ▀▄.▀··██ ▐███▪·██ ▐███▪▐█ ▀█ 
# ▐▀▀▪▄▐█ ▌▐▌▐█·▐█ ▌▐▌▐█·▄█▀▀█ 
# ▐█▄▄▌██ ██▌▐█▌██ ██▌▐█▌▐█ ▪▐▌
#  ▀▀▀ ▀▀  █▪▀▀▀▀▀  █▪▀▀▀ ▀  ▀
# © 2021 Emma Campbell
# 
# Permission is hereby granted, free of charge, to any person obtaining 
# a copy of this software and associated documentation files (the 
# "Software"), to deal in the Software without restriction, including 
# without limitation the rights to use, copy, modify, merge, publish, 
# distribute, sublicense, and/or sell copies of the Software, and to 
# permit persons to whom the Software is furnished to do so, subject 
# to the following conditions:
#
# The above copyright notice and this permission notice shall be 
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, 
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF 
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY 
# CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, 
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE 
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
export ZSH="$HOME/.ohmyzsh"
export DOTFILES="$HOME/.dotfiles"
export PROJECTS="$HOME/coding"

export LSCOLORS='exfxcxdxbxegedabagacad'
export CLICOLOR=true

DEFAULT_USER="$(whoami)"
ZSH_THEME="typewritten"
TYPEWRITTEN_PROMPT_LAYOUT="singleline_verbose"

declare -a plugins=(zsh-autosuggestions zsh-syntax-highlighting git brew docker docker-compose)

## NVM path (should be before sourcing zsh)
export NVM_LAZY_LOAD=true
export NVM_AUTO_USE=true

if [ -d "$HOME/.ohmyzsh" ];
then
    source "$ZSH/oh-my-zsh.sh"
fi

source ~/.aliases

if [[ -a ~/.localrc ]];
then
	source ~/.localrc
fi

