#!/bin/zsh
#
# ▄▄▄ .• ▌ ▄ ·. • ▌ ▄ ·.  ▄▄▄· 
# ▀▄.▀··██ ▐███▪·██ ▐███▪▐█ ▀█ 
# ▐▀▀▪▄▐█ ▌▐▌▐█·▐█ ▌▐▌▐█·▄█▀▀█ 
# ▐█▄▄▌██ ██▌▐█▌██ ██▌▐█▌▐█ ▪▐▌
#  ▀▀▀ ▀▀  █▪▀▀▀▀▀  █▪▀▀▀ ▀  ▀
# © 2020 Emma Campbell
# 
# Permission is hereby granted, free of charge, to any person obtaining 
# a copy of this software and associated documentation files (the 
# "Software"), to deal in the Software without restriction, including 
# without limitation the rights to use, copy, modify, merge, publish, 
# distribute, sublicense, and/or sell copies of the Software, and to 
# permit persons to whom the Software is furnished to do so, subject 
# to the following conditions:
#
# The above copyright notice and this permission notice shall be 
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, 
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF 
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY 
# CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, 
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE 
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

export PATH=/Users/emma/.npm-global/bin:$HOME/bin:/usr/local/bin:$PATH
export PATH="$HOME/.yarn/bin:$PATH"

export ZSH="$HOME/.ohmyzsh"
export DOTFILES="$HOME/.dotfiles"
export PROJECTS="$HOME/coding"

export LSCOLORS='exfxcxdxbxegedabagacad'
export CLICOLOR=true

DEFAULT_USER="$(whoami)"
ZSH_THEME="typewritten"
declare -a plugins=(zsh-autosuggestions zsh-syntax-highlighting zsh-apple-touchbar git brew docker docker-compose)

## NVM path (should be before sourcing zsh)
export NVM_LAZY_LOAD=true
export NVM_AUTO_USE=true

if [ -d "$HOME/.ohmyzsh" ];
then
    . "$ZSH/oh-my-zsh.sh"
fi

. ~/.aliases.zsh

if [[ -a ~/.localrc ]];
then
	. ~/.localrc
fi

# Adding path for MJ
export PATH="$PATH:/usr/local/smlnj/bin"


export PATH="/usr/local/opt/python@3.8/bin:$PATH"
export PATH="/Users/emma/Library/Python/3.8/bin:$PATH"
export PATH="/usr/local/opt/ncurses/bin:$PATH"

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

export PATH="/usr/local/opt/llvm/bin:$PATH"

neofetch
