#!/bin/bash

## NVM path (should be before sourcing zsh)
export NVM_LAZY_LOAD=true
export NVM_AUTO_USE=true

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"                   # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" # This loads nvm bash_completion

# I keep running into a `ENETUNREACH` error
# when trying to use anything having to do with
# NPM on node 18. According to stack overflow,
# using ipv4 instead of ipv6 should resolve this.
export NODE_OPTIONS="--dns-result-order=ipv4first"

# Add global yarn path
export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

if [[ -e ~/.node.local ]]; then
	source ~/.node.local
fi
