#!/usr/bin/env bash
#
# Run all dotfile installers
set -e

export DOTFILES="$HOME/.dotfiles"
cd $DOTFILES

# find the installers and run them iteratively
find $DOTFILES -name install.sh | while read installer ; do sh -c "${installer}" ; done
